### ISSUE TITLE
simulation log format different in 2.1.7

### ISSUE THREAD

**Issue by stefanleh** [henri-tremblay/gatling-parser#1]
unfortunately the parser doesnt work with 2.1.7 files
[simulation.zip](https://github.com/henri-tremblay/gatling-parser/files/152439/simulation.zip)

**Comment by henri-tremblay** [comment]
Yes. Indeed. I tried to update it but tried to do something too complicated. For some new needs I had. But for fun I will just make it work first.

Or have you already fixed your problem?
